from __future__ import annotations

from datetime import datetime, timedelta
from pathlib import Path
from typing import List

import feedparser
import yaml

from scripts.models import NewsItem
from scripts.utils_history import append_history, get_recent_ids
from scripts.llm_client import summarize_news_items


FEEDS = [
    # Broad AI/tech feeds.
    "https://techcrunch.com/category/artificial-intelligence/feed/",
    "https://www.theverge.com/ai-artificial-intelligence/rss/index.xml",
    "https://www.wired.com/feed/tag/ai/latest/rss",
]
WEEKLY_READS_PATH = Path("config/weekly_reads_pending.yml")


def _fetch_candidate_articles(issue_date: datetime) -> List[dict]:
    """
    Fetch recent articles from a small set of feeds and return simplified dicts.
    """
    one_week_ago = issue_date - timedelta(days=7)
    items: List[dict] = []

    for url in FEEDS:
        feed = feedparser.parse(url)
        for entry in getattr(feed, "entries", []):
            link = getattr(entry, "link", "") or ""
            title = getattr(entry, "title", "") or ""
            summary = getattr(entry, "summary", "") or ""

            published_parsed = getattr(entry, "published_parsed", None)
            if published_parsed:
                published_dt = datetime(
                    published_parsed.tm_year,
                    published_parsed.tm_mon,
                    published_parsed.tm_mday,
                )
                if published_dt < one_week_ago:
                    continue

            if not link or not title:
                continue

            items.append(
                {
                    "title": title,
                    "url": link,
                    "description": summary,
                }
            )

    return items


def _fallback_from_weekly_reads() -> List[dict]:
    """
    If no feed items were found, reuse Weekly Reads links as a fallback pool
    so the section is never empty.
    """
    if not WEEKLY_READS_PATH.exists():
        return []
    with WEEKLY_READS_PATH.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or []
    if not isinstance(data, list):
        return []

    items: List[dict] = []
    for entry in data[:5]:
        title = (entry or {}).get("title") or ""
        url = (entry or {}).get("url") or ""
        if title and url:
            items.append({"title": title, "url": url, "description": ""})
    return items


def run(issue_date: datetime) -> List[NewsItem]:
    """
    Build up to 5 broadly understandable AI news items from the past week,
    with titles and summaries generated by Claude.
    """
    recent_ids = get_recent_ids("news")

    candidates = _fetch_candidate_articles(issue_date)
    if not candidates:
        candidates = _fallback_from_weekly_reads()
    candidates = [c for c in candidates if c.get("url") not in recent_ids]

    # Keep at most 8–10 for the LLM to process
    candidates = candidates[:10]

    enriched = summarize_news_items(candidates)

    items: List[NewsItem] = []
    for article in enriched:
        url = article.get("url") or ""
        if not url:
            continue

        title = article.get("title") or "AI update"
        summary_paragraphs = article.get("summary_paragraphs") or []

        items.append(
            NewsItem(
                title=title,
                source_url=url,
                summary_paragraphs=summary_paragraphs,
            )
        )

        if len(items) >= 5:
            break

    append_history("news", [i.source_url for i in items], issue_date.date().isoformat())
    return items

