from __future__ import annotations

from datetime import datetime, timedelta
from typing import List

import feedparser

from scripts.models import NewsItem
from scripts.utils_history import append_history, get_recent_ids
from scripts.llm_client import summarize_news_items


FEEDS = [
    # Broad tech/AI-focused feeds. You can adjust these as you like.
    "https://www.reutersagency.com/feed/?best-topics=technology",
    "https://blogs.nvidia.com/feed/",
]


def _fetch_candidate_articles(issue_date: datetime) -> List[dict]:
    """
    Fetch recent articles from a small set of feeds and return simplified dicts.
    """
    one_week_ago = issue_date - timedelta(days=7)
    items: List[dict] = []

    for url in FEEDS:
        feed = feedparser.parse(url)
        for entry in getattr(feed, "entries", []):
            link = getattr(entry, "link", "") or ""
            title = getattr(entry, "title", "") or ""
            summary = getattr(entry, "summary", "") or ""

            published_parsed = getattr(entry, "published_parsed", None)
            if published_parsed:
                published_dt = datetime(
                    published_parsed.tm_year,
                    published_parsed.tm_mon,
                    published_parsed.tm_mday,
                )
                if published_dt < one_week_ago:
                    continue

            if not link or not title:
                continue

            items.append(
                {
                    "title": title,
                    "url": link,
                    "description": summary,
                }
            )

    return items


def run(issue_date: datetime) -> List[NewsItem]:
    """
    Build up to 5 broadly understandable AI news items from the past week,
    with titles and summaries generated by Claude.
    """
    recent_ids = get_recent_ids("news")

    candidates = _fetch_candidate_articles(issue_date)
    candidates = [c for c in candidates if c.get("url") not in recent_ids]

    # Keep at most 8–10 for the LLM to process
    candidates = candidates[:10]

    enriched = summarize_news_items(candidates)

    items: List[NewsItem] = []
    for article in enriched:
        url = article.get("url") or ""
        if not url:
            continue

        title = article.get("title") or "AI update"
        summary_paragraphs = article.get("summary_paragraphs") or []

        items.append(
            NewsItem(
                title=title,
                source_url=url,
                summary_paragraphs=summary_paragraphs,
            )
        )

        if len(items) >= 5:
            break

    append_history("news", [i.source_url for i in items], issue_date.date().isoformat())
    return items

