- title: Open AI on a funding spree
  url: https://openai.com/index/accelerating-the-next-phase-ai/
  note: Yet another funding round for OpenAI, yet another record raise. "Next Phase of AI" - what could that be

- title: But Claude's the one doing the heavy lifting
  url: https://mythos-5.org/
  note: Claude launched a new model, aptly named "Mythos", a step function increase in everything we see today, and a massive jump in cybersecurity. Cyber Sec stocks took a big tumble.

- title: Microsoft with a big Japanese advantage
  url: https://www.reuters.com/business/media-telecom/microsoft-invest-10-billion-japan-ai-cyber-defence-expansion-2026-04-03/
  note: Microsoft goes big on Japan, $10 Bn infusion to expand ‌artificial intelligence infrastructure and strengthen cybersecurity cooperation with the government.
