# Add up to ~8–10 candidate social posts per week.
# Example:
# - platform: x
#   handle: example_handle
#   url: https://x.com/example/status/123
#   note: Optional note for context

- platform: x
  handle: DramaAlert
  url: https://x.com/DramaAlert/status/2033939940753461381?s=20
  note: Youtube took a strong stand against AI by asking users to label videos - my take - I feel that they're getting their data labeled by us
  
- platform: x
  handle: stitchbygoogle
  url: https://x.com/stitchbygoogle/status/2034332847893574080
  note: Google rolled out Stitch, a new tool to help generate UI, hit or miss? Figma stock tumbled

- platform: linkedin
  handle: marie-schneegans
  url: https://www.linkedin.com/posts/marie-schneegans_michael-and-i-are-separating-romantically-activity-7439718578100187136-0oio/
  note: Has LinkedIn become the new Facebook? Is this what people post on LinkedIn now?

- platform: x
  handle: katiemiller
  url: https://x.com/KatieMiller/status/2037520112996024801?s=20
  note: Has AI finally lost it, what happened to guardrails

- platform: x
  handle: claudeai
  url: https://x.com/claudeai/status/2036195789601374705
  note: Anthropic have been shipping like a machine, new updates literally every day - this one basically gives Claude control over your computer. Sit back and let AI do everything

- platform: x
  handle: soraofficial app
  url: https://x.com/soraofficialapp/status/2036546752535470382
  note: Bye Bye Sora, OpenAI seems to be closing down everything else, trying to focus on its core business, which has seen a big tumble
