- platform: x                  
  handle: nic_carter             
  url: https://x.com/nic_carter/status/2039687558775370065
  note: People are going crazy on X after seeing someone actually vibe code a unicorn. This is living proof that vibe coding has already become next big thing.

- platform: x
  handle: fried_rice
  url: https://x.com/Fried_rice/status/2038894956459290963
  note: This one's big. I mean really big. 34M views. Claude Code's source code was somehow leaked. And what followed was a crazy episode. Almost everyone cloned the repo, someone ported it to python, Claude tried to lawyer up, stay tuned. 
