- title: Every Building you've been in has been designed by software
  url: https://www.a16z.news/p/every-building-youve-ever-been-in?

- title: What I learned getting companies to use AI
  url: https://every.to/also-true-for-humans/seven-things-i-ve-learned-getting-companies-to-use-ai
