- title: The next billion of AI
  url: https://www.a16z.news/p/the-sovereign-wall-why-ais-next-billion?

- title: ChatGPT curing cancer?
  url: https://x.com/paul_conyngham/status/2036940410363535823

- title: OpenAI new researcher
  url: https://www.technologyreview.com/2026/03/20/1134438/openai-is-throwing-everything-into-building-a-fully-automated-researcher/
